import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/public/css/global.css";
import { parsePost } from "./Logic/grayMatterLogic/gray";
import path from "path";
import { sync } from "glob";

const BASE_PATH = "/app/posts";
const POSTS_PATH = path.join(process.cwd(), BASE_PATH);

export const getPostPaths = (category?: string) => {
  const folder = category || "**";
  const paths: string[] = sync(`${POSTS_PATH}/${folder}/**/*.mdx`);
  return paths;
};

const inter = Inter({ subsets: ["latin"] });
const data = getPostPaths();
data.map((item) => parsePost(item));
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
